### PR TITLE
Modern JS refactor

### PR DESCRIPTION
**Pull request by dgreene-r7**
This PR represents a large refactoring effort to 
1) migrate the codebase to modern JS, and 
2) to remove the spaghetti-code mess of ejs templates and bad frontend JS in favor of a modern React/Redux driven webapp.

This PR also implements an updated settings structure for `aws` keys. Instead of providing an object with region -> key mappings, we provide an array, like so:
```json
"aws": [
    {
      "account": "",
      "region": "",
      "key": ""
    },
    {
      "account": "",
      "region": "",
      "key": ""
    }
  ]
```

### CODE REVIEW

**Comment by dgreene-r7** [comment]
Btw I'm so, so, so sorry for how large this PR is.

**Comment by athompson-r7** [comment]
It is possible to split the new settings structure into it's own PR so that this is only code refactoring?

**Comment by dgreene-r7** [comment]
The problem is that most of the work required to update the settings structure is realized in the front-end. 

What I could do is open a PR with the old views removed, the settings structure implemented and the back-end refactor, then a separate one for the client. Only downside is that it would leave master in an unusable state between the time that those PRs were merged.

**Comment by dgreene-r7** [comment]
I think that's pretty reasonable.

**Comment by dgreene-r7** [comment]
#41 is the PR for *only* the refactor. Closing this PR as a result and will open others for the rest of the work.

**Pull request closed without merging**
